bookstore/urls.py
from django.urls import path, include
from .import views
from django_private_chat import urls as django_private_chat_urls

app_name = 'bookstore'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<username>/', views.profile, name='profile'),
    path('mystore/', views.mystore, name='mystore'),
    path('user_store/<username>/', views.user_store, name='user_store'),
    path('user_wishlist/<username>/', views.user_wishlist, name='user_wishlist'),
    path('mycart/', views.mycart, name='mycart'),
    path('mywishlist/', views.mywishlist, name='mywishlist'),
    path('myorders/', views.myorders, name='myorders'),
    path('received_orders/', views.received_orders, name='received_orders'),
    path('thanks/', views.thanks, name='thanks'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('register/', views.MyRegistrationView.as_view(), name='register'),
    path('book/add/', views.add_book, name='add_book'),
    path('book/remove/<int:book_id>/', views.remove_book, name='remove_book'),
    path('book/edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('cart/add/<int:book_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:cart_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/do_purchase/<int:cart_id>', views.do_purchase, name='do_purchase'),
    path('cart/confirm_purchase/<int:cart_id>/', views.confirm_purchase, name='confirm_purchase'),
    path('cart/increase/<int:cart_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:cart_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('wishlist/add/<int:book_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:wishlist_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('order/complete/<int:order_id>/', views.complete_order, name='complete_order'),
    
    path('', include(django_private_chat_urls)),
    
    path('test/', views.test, name='test')
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django_private_chat import urls as django_private_chat_urls
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('bookstore:index')), name='index'),
    path('admin/', admin.site.urls),
    path('bookstore/', include('bookstore.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from datetime import datetime

# Create your models here.
# Logics for creating and deletion and in terms of forms

def cover_upload_path(instance, filename):
    return os.path.join('books', instance.seller.username, filename)

class Book(models.Model):
    
    # category choices
    COMPUTER = 'COM'
    MATH = 'MATH'
    PHYSICS = 'PHYSICS'
    OTHER = 'OTHER'
    CATEGORY_CHOICES = [
        (COMPUTER, 'computer'),
        (MATH, 'math'),
        (PHYSICS, 'physics'),
        (OTHER, 'other')
    ]
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    orig_price = models.DecimalField(decimal_places=2, max_digits=10)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    cover_image = models.ImageField(upload_to=cover_upload_path)
    description = models.TextField(default='no description')
    
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    isbn = models.CharField(max_length=13)
    
    def __str__(self):
        return '{}, by {}.'.format(self.title, self.author)
    
    def get_link_to_douban(self):
        return 'http://douban.com/isbn/{}/'.format(self.isbn)
    

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    
    date_added = models.DateTimeField()
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return "Title: {title}, Date: {date}, Quantity: {quantity}".format(
            title=str(self.book.title),
            date=datetime.now().strftime('%Y-%m-%d'),
            quantity=self.quantity
        )
    
class OrderItem(models.Model):
    # status choices
    PROCESSING = 'PR'
    COMPLETED = 'CO'
    STATUS_CHOICES = [
        (PROCESSING, 'processing'),
        (COMPLETED, 'completed')
    ]
    # delivery methods
    SHIPPING = 'SH'
    OFFLINE = 'OF'
    DELIVERY_CHOICES = [
        (SHIPPING, 'shipping'),
        (OFFLINE, 'offline')
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    delivery_method = models.CharField(max_length=20, choices=DELIVERY_CHOICES)
    
    def __str__(self):
        return 'Title: {}, Quantity: {}, Status: {}, Delivery method: {}'.format(
            self.book.title,
            self.quantity,
            self.get_status_display(),
            self.get_delivery_method_display()
        )
    
    def is_completed(self):
        return self.status == self.COMPLETED
    
class WishListItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_added = models.DateTimeField(null=True)
    description = models.TextField(default='no description')
    
    def __str__(self):
        return "Title: {title}, Date: {date}".format(
            title=str(self.book.title),
            date=datetime.now().strftime('%Y-%m-%d'),
        )
    

bookstore/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class BookForm(ModelForm):
    class Meta:
        model = Book
        exclude = ['seller']
        

class CartItemForm(ModelForm):
    class Meta:
        model = CartItem
        fields = '__all__'

class OrderItemForm(ModelForm):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    # book = models.ForeignKey(Book, on_delete=models.CASCADE)
    # quantity = models.PositiveIntegerField(default=1)
    # date_added = models.DateTimeField(null=True)
    # status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    # delivery_method = models.CharField(max_length=20, choices=DELIVERY_CHOICES)
    class Meta:
        model = OrderItem
        fields = ['delivery_method']

class WishListItemForm(ModelForm):
    class Meta:
        model = WishListItem
        fields = '__all__'
        
        
class SearchForm(forms.Form):
    ALL = 'ALL'
    CATEGORY_CHOICES = [(ALL, 'all')] + Book.CATEGORY_CHOICES
    keywords = forms.CharField(max_length=100, required=False)
    category = forms.ChoiceField(choices=CATEGORY_CHOICES)
    
        
    
    
        
    

bookstore/views.py
from django.shortcuts import render, redirect
from django_registration.views import RegistrationView
from django_registration.forms import RegistrationFormUniqueEmail
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseNotModified
from django.shortcuts import get_object_or_404
from .forms import *
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django_registration.signals import user_registered
import django
from collections import OrderedDict
import datetime

# Create your views here.

def index(request):
    # if request.user.is_authenticated:
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            booklist = Book.objects.all()
            words = form.cleaned_data['keywords'].split()
            for word in words:
                booklist = Book.objects.filter(title__icontains=word)
            category = form.cleaned_data['category']
            if category != SearchForm.ALL:
                booklist = booklist.filter(category=category)
    else:
        form = SearchForm()
        booklist = Book.objects.all()
    return render(request, 'bookstore/index.html', {'booklist': booklist, 'form': form})
    # else:
    #     return redirect('bookstore:login')
    
@login_required
def mystore(request):
    booklist = Book.objects.filter(seller=request.user)
    return render(request, 'bookstore/mystore.html', {'booklist': booklist})

@login_required
def user_store(request, username):
    booklist = Book.objects.filter(seller__username=username)
    return render(request, 'bookstore/user_store.html', {'booklist': booklist, 'username': username})
    
@login_required
def mycart(request):
    cartlist = CartItem.objects.filter(user=request.user)
    return render(request, 'bookstore/mycart.html', {'cartlist': cartlist})

@login_required
def mywishlist(request):
    wishlist = WishListItem.objects.filter(user=request.user)
    return render(request, 'bookstore/mywishlist.html', {'wishlist': wishlist})

@login_required
def user_wishlist(request, username):
    wishlist = WishListItem.objects.filter(user__username=username)
    return render(request, 'bookstore/user_wishlist.html', {'wishlist': wishlist, 'username': username})

def thanks(request):
    return render(request, 'bookstore/thanks.html')
    # return HttpResponse('<h1>Thanks!</h1>')

class MyLoginView(auth_views.LoginView):
    # pass
    extra_context = {
        'next': lambda: reverse('bookstore:index')
    }
    
class MyLogoutView(auth_views.LogoutView):
    next_page = reverse_lazy('bookstore:index')
    
    
class MyRegistrationView(RegistrationView):
    success_url = reverse_lazy('bookstore:login')
    template_name = 'registration/registration_form.html'
    form_class = RegistrationFormUniqueEmail
    
    def register(self, form):
        data = form.cleaned_data
        user = User.objects.create_user(
            username=data['username'],
            email=data['email'],
            password=data['password1'])
        user_registered.send(self.__class__, user=user)
        return user
    
    
@login_required
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        # form.seller = request.user
        if form.is_valid():
            book = form.save(commit=False)
            book.seller = request.user
            book.save()
            return redirect('bookstore:mystore')
    else:
        form = BookForm()
        
    return render(request, 'bookstore/add_book.html', {'form': form})

@login_required
def edit_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save(commit=False)
            book.save()
            return redirect('bookstore:mystore')
    else:
        form = BookForm(instance=book)
    
    return render(
        request,
        'bookstore/edit_book.html',
        {'form': form, 'pk': book.pk})

@login_required
def remove_book(request, book_id):
    if request.method == 'POST':
        books = Book.objects.filter(pk=book_id)
        books.delete()
        return redirect('bookstore:mystore')
    else:
        raise Http404('Invalid query method')
    
@login_required
def increase_quantity(request, cart_id):
    if request.method == 'POST':
        cart_item = get_object_or_404(CartItem, pk=cart_id)
        # if cart_item.quantity + amount < 0:
        #     cart_item.quantity = 0
        # else:
        cart_item.quantity += 1
        cart_item.save()
        return redirect('bookstore:mycart')
    else:
        raise Http404('Invalid query method')

@login_required
def decrease_quantity(request, cart_id):
    if request.method == 'POST':
        cart_item = get_object_or_404(CartItem, pk=cart_id)
        if cart_item.quantity  > 1:
            cart_item.quantity -= 1
            cart_item.save()
        return redirect('bookstore:mycart')
    else:
        raise Http404('Invalid query method')

@login_required
def add_to_cart(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        # check whether the book already exists, otherwise create it
        (cart_item, created) = CartItem.objects.get_or_create(
            user=request.user,
            book=book,
            defaults={
                'date_added': datetime.datetime.now(),
                'quantity': 1
            }
        )
        if not created:
            # already exists
            cart_item.quantity += 1
            cart_item.save()
        return redirect('bookstore:index')
    else:
        raise Http404('Invalid method "{}"'.format(request.method))

@login_required
def remove_from_cart(request, cart_id):
    if request.method == 'POST':
        # check whether the book already exists, otherwise create it
        cartlist = CartItem.objects.filter(id=cart_id)
        cartlist.delete()
        return redirect('bookstore:mycart')
    else:
        raise Http404('Invalid method "{}"'.format(request.method))
    
@login_required
def add_to_wishlist(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        # check whether the book already exists, otherwise create it
        (cart_item, created) = WishListItem.objects.get_or_create(
            user=request.user,
            book=book,
            defaults={
                'date_added': datetime.datetime.now(),
            }
        )
        return redirect('bookstore:index')
    else:
        raise Http404('Invalid method "{}"'.format(request.method))

@login_required
def remove_from_wishlist(request, wishlist_id):
    if request.method == 'POST':
        # check whether the book already exists, otherwise create it
        wishlist = WishListItem.objects.filter(id=wishlist_id)
        wishlist.delete()
        return redirect('bookstore:mywishlist')
    else:
        raise Http404('Invalid method "{}"'.format(request.method))
    
@login_required
def confirm_purchase(request, cart_id):
    cart_item = get_object_or_404(CartItem, pk=cart_id)
    order_fields = [
        ('Book title', cart_item.book.title),
        ('Quantity', cart_item.quantity),
    ]
    
    form = OrderItemForm()
    
    return render(request, 'bookstore/confirm_purchace.html',
                  {'order_fields': order_fields, 'form': form, 'cart_id': cart_item.id})

@login_required
def do_purchase(request, cart_id):
    cart_item = get_object_or_404(CartItem, pk=cart_id)
    if request.method == 'POST':
        order_fields = {
            'user': request.user,
            'book': cart_item.book,
            'quantity': cart_item.quantity,
            'date_added': datetime.datetime.now(),
            'status': OrderItem.PROCESSING,
            'delivery_method': OrderItem.SHIPPING
        }
        form = OrderItemForm(request.POST)
        if form.is_valid():
            order = OrderItem.objects.create(**order_fields)
            order.delivery_method = form.cleaned_data['delivery_method']
            order.save()
            CartItem.objects.filter(id=cart_id).delete()
            return redirect('bookstore:thanks')
        return render(request, 'bookstore/confirm_purchace.html',
                      {'form': form})
    else:
        raise Http404('Invalid request method')
    
@login_required
def myorders(request):
    orderlist = OrderItem.objects.filter(user=request.user).order_by('date_added')
    return render(request, 'bookstore/myorders.html', {'orderlist': orderlist})

@login_required
def received_orders(request):
    orderlist = OrderItem.objects.filter(book__seller=request.user).order_by('date_added')
    return render(request, 'bookstore/received_orders.html', {'orderlist': orderlist})

@login_required
def complete_order(request, order_id):
    if request.method == 'POST':
        order = get_object_or_404(OrderItem, id=order_id)
        order.status = OrderItem.COMPLETED
        order.save()
        return redirect('bookstore:myorders')
    else:
        raise Http404('Invalid request method')

@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    wishlist = WishListItem.objects.filter(user=user)
    context = {
        'username': user.username,
        'email': user.email,
        'wishlist': wishlist
    }
    return render(request, 'bookstore/profile.html', context)

def test(request):
    class TestForm(forms.Form):
        name = forms.CharField(max_length=100)
        hello = forms.CharField(max_length=100)
    form = TestForm()
    return render(request, 'bookstore/test.html', {'form': form})

bookstore/templates/bookstore/add_book.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<form action="{% url  'bookstore:add_book' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'snippets/form_snippets.html' %}
  {% bootstrap_button "Add" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

bookstore/templates/bookstore/index.html
{%  extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>All Books</h1>
    <div class="panel">
      <form action="{% url 'bookstore:index' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Search" button_type="submit" button_class="btn-primary" %}
      </form>
    </div>
    <ul>
    {% for book in booklist %}
      <ol class="list-group">
        <li class="list-group-item" >
            <div class="media" style="overflow-x: auto">
              <div class="row">
                <div class="media-left media-middle">
                  <img src="{{ book.cover_image.url }}" class="media-object" style="width:200px">
                </div>
                <div class="media-body">
                  <h3 class="media-heading">{{ book.title }}</h3>
                  <p>by <strong>{{ book.author }}</strong></p>
                  <div class="container-fluid">
                    <div class="row">
                      <div class="col-sm-6">
                        <ol class="list-group">
                          <li class="list-group-item"><label>Price: </label> &yen {{ book.price }}</li>
                          <li class="list-group-item"><label>Original: </label> &yen  {{ book.orig_price }}</li>
                          <li class="list-group-item"><label>Cateogry:</label> {{ book.get_category_display }}</li>
                          <li class="list-group-item"><label>Seller:</label> {{ book.seller.username }}</li>
                          <li class="list-group-item"><label>ISBN:</label>
                            {{ book.isbn }}
                            <a class="btn btn-info" href="{{ book.get_link_to_douban }}" target="_blank">Link to Douban</a>
                          </li>
                          <li class="list-group-item"><label>Description:</label> {{ book.description }}</li>
                        </ol>
                      </div>
                      <div class="col-sm-6">
                        <ol class="list-group">
                          <li class="list-group-item">
                            <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:profile' book.seller.username %}">View seller profile</a>
                          </li>
                          <li class="list-group-item">
                            <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:dialogs_detail' book.seller.username %}">Contact seller</a>
                          </li>
                          <li class="list-group-item">
                            <form class="form-inline" action="{% url 'bookstore:add_to_cart' book.id %}" method="post">
                              {% csrf_token %}
                              <button class="btn btn-primary" style="width:100%" type="submit">Add to cart </button>
                            </form>
                          </li>
                          <li class="list-group-item">
                            <form class="form-inline" action="{% url 'bookstore:add_to_wishlist' book.id %}" method="post">
                              {% csrf_token %}
                              <button class="btn btn-primary" style="width:100%" type="submit">Add to wishlist </button>
                            </form>

                          </li>
                        </ol>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

          </div>
        </li>
      </ol>
    {% endfor %}
    </ul>


{% endblock %}

bookstore/templates/bookstore/mycart.html
{%  extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div id="app">
  <div>
  <h1>My Shopping Cart</h1>
    <ul>
    {% for cart_item in cartlist %}
      <ol  class="list-group">
        <li class="list-group-item">
          <div class="media" style="overflow-x: auto">
            <div class="media-left media-middle">
              <img src="{{ cart_item.book.cover_image.url }}" class="media-object" style="width:200px">
              <br/>
            </div>
            <div class="media-body">
              <h3 class="media-heading">{{ cart_item.book.title }}</h3>
              <p>by <strong>{{ cart_item.book.author }}</strong></p>
              <div class="container-fluid">
                <div class="row">
                  <div class="col-sm-6">
                    <ol class="list-group">
                      <li class="list-group-item"><label>Price: </label>: &yen {{ cart_item.book.price }}</li>
                      <li class="list-group-item"><label>Original: </label> &yen  {{ cart_item.book.orig_price }}</li>
                      <li class="list-group-item"><label>Cateogry:</label> {{ cart_item.book.get_category_display }}</li>
                      <li class="list-group-item"><label>Seller:</label> {{ cart_item.book.seller.username }}</li>
                      <li class="list-group-item"><label>ISBN:</label>
                        {{ book.isbn }}
                        <a class="btn btn-info" href="{{ cart_item.book.get_link_to_douban }}" target="_blank">Link to Douban</a>
                      </li>
                      <li class="list-group-item"><label>Description:</label> {{ cart_item.book.description }}</li>
                    </ol>
                  </div>
                  <div class="col-sm-6">
                    <ol class="list-group">
                      <li class="list-group-item">
                        <label>Quantity:</label>
                        <form action="{% url 'bookstore:increase_quantity' cart_item.id %}" style="display:inline" method="post">
                          {% csrf_token %}
                          <button class="btn btn-default" type="submit">+</button>
                        </form>
                        {{ cart_item.quantity }}
                        <form action="{% url 'bookstore:decrease_quantity' cart_item.id %}" style="display:inline" method="post">
                          {% csrf_token %}
                          <button class="btn btn-default" type="submit">-</button>
                        </form>
                      </li>
                      <li class="list-group-item">
                        <label>Date added: </label> {{ cart_item.date_added }}
                      </li>
                      <li class="list-group-item">
                        <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:profile' cart_item.book.seller.username %}">View seller profile</a>
                      </li>
                      <li class="list-group-item">
                        <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:dialogs_detail' cart_item.book.seller.username %}">Contact seller</a>
                      </li>
                      <li class="list-group-item">
                        <form action="{% url 'bookstore:confirm_purchase' cart_item.id %}" method="get">
                          {% csrf_token %}
                          <button class="btn btn-primary" style="width:100%">Purchase</button>
                        </form>
                      </li>
                      <li class="list-group-item">
                        <form action="{% url 'bookstore:remove_from_cart' cart_item.id %}" method="post">
                          {% csrf_token %}
                          <button class="btn btn-danger" style="width:100%">Remove</button>
                        </form>
                      </li>
                    </ol
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ol>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

bookstore/templates/bookstore/mystore.html
{%  extends 'base.html' %}
{% block content %}
<div id="app">
  <div>
    <h1>My Store</h1>
    <div class="well">
        <a class="btn btn-primary" style="width:100%" href="{% url 'bookstore:add_book' %}">Add new book</a>
    </div>
    <ul>
    {% for book in booklist %}
      <ol class="list-group">
        <li class="list-group-item">
{#          <div class="media">#}
          <div class="media" style="overflow-x: auto">
            <div class="media-left media-middle">
              <img src="{{ book.cover_image.url }}" class="media-object" style="width:200px">
              <br/>
            </div>
            <div class="media-body">
              <h3 class="media-heading">{{ book.title }}</h3>
              <p>by <strong>{{ book.author }}</strong></p>
              <div class="container-fluid">
                <div class="row">
                  <div class="col-sm-6">
                    <ol class="list-group">
                      <li class="list-group-item"><label>Price: </label>: &yen {{ book.price }}</li>
                      <li class="list-group-item"><label>Original: </label> &yen  {{ book.orig_price }}</li>
                      <li class="list-group-item"><label>Cateogry:</label> {{ book.get_category_display }}</li>
                      <li class="list-group-item"><label>Seller:</label> {{ book.seller.username }}</li>
                      <li class="list-group-item"><label>ISBN:</label>
                        {{ book.isbn }}
                        <a class="btn btn-info" href="{{ book.get_link_to_douban }}" target="_blank">Link to Douban</a>
                      </li>
                      <li class="list-group-item"><label>Description:</label> {{ book.description }}</li>
                    </ol>
                  </div>
                  <div class="col-sm-6">
                    <ol class="list-group">
                      <li class="list-group-item">
                        <form action="{% url 'bookstore:edit_book' book.id %}" method="get">
                          {% csrf_token %}
                          <button class="btn btn-primary" style="width:100%" type="submit">Edit </button>
                        </form>
                      </li>
                      <li class="list-group-item">
                        <form action="{% url 'bookstore:remove_book' book.id %}" method="post">
                          {% csrf_token %}
                          <button class="btn btn-danger" style="width:100%" type="submit">Remove</button>
                        </form>
                      </li>
                    </ol>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ol>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

bookstore/templates/bookstore/profile.html
{#{%  extends 'base.html' %}#}
{%  extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}

<h1> User Info</h1>
  <ul class="list-group">

    <li class="list-group-item">
      <label>Username: </label> {{ username }}
    </li>
    <li class="list-group-item">
      <label>Email: </label> {{ email }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'bookstore:user_store' username %}">View <strong>{{ username }}</strong>'s store</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'bookstore:user_wishlist' username %}">View <strong>{{ username }}</strong>'s wishlist</a>
    </li>
  </ul>
{#<h1>{{ username }}'s wishlist</h1>#}
{#<ul>#}
{#{% for item in wishlist %}#}
{#  <ol class="list-group">#}
{#    <li class="list-group-item">#}
{#      <div class="media">#}
{#        <div class="media-left media-middle">#}
{#          <img src="{{ item.book.cover_image.url }}" class="media-object" style="width:200px">#}
{#          <br/>#}
{#        </div>#}
{#        <div class="media-body">#}
{#          <h3 class="media-heading">{{ item.book.title }}</h3>#}
{#          <p>by <strong>{{ item.book.author }}</strong></p>#}
{#          <div class="container-fluid">#}
{#            <div class="row">#}
{#              <div class="col-sm-6">#}
{#                <ol class="list-group">#}
{#                  <li class="list-group-item"><label>Price: </label>: &yen {{ item.book.price }}</li>#}
{#                  <li class="list-group-item"><label>Original: </label> &yen  {{ item.book.orig_price }}</li>#}
{#                  <li class="list-group-item"><label>Cateogry:</label> {{ item.book.get_category_display }}</li>#}
{#                  <li class="list-group-item"><label>Seller:</label> {{ item.book.seller.username }}</li>#}
{#                  <li class="list-group-item"><label>ISBN:</label>#}
{#                    {{ book.isbn }}#}
{#                    <a class="btn btn-info" href="{{ item.book.get_link_to_douban }}" target="_blank">Link to Douban</a>#}
{#                  </li>#}
{#                  <li class="list-group-item"><label>Description:</label> {{ item.book.description }}</li>#}
{#                </ol>#}
{#              </div>#}
{#              <div class="col-sm-6">#}
{#                <ol class="list-group">#}
                  {#                      <li class="list-group-item">#}
                  {#                        <form action="{% url 'bookstore:confirm_purchase' item.id %}" method="get">#}
                  {#                          {% csrf_token %}#}
                  {#                          <button class="btn btn-primary" style="width:100%">Purchase</button>#}
                  {#                        </form>#}
                  {#                      </li>#}
{#                  <li class="list-group-item">#}
{#                    <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:profile' item.book.seller.username %}">View seller profile</a>#}
{#                  </li>#}
{#                  <li class="list-group-item">#}
{#                    <a class="btn btn-info" style="width:100%" href="{% url 'bookstore:dialogs_detail' item.book.seller.username %}">Contact seller</a>#}
{#                  </li>#}
{#                </ol>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </li>#}
{#  </ol>#}
{#{% endfor %}#}
{#</ul>#}
{% endblock %}

bookstore/templates/bookstore/thanks.html
{% extends 'base.html' %}
{% block content %}
  <h1>Thanks for your purchase!</h1>
{% endblock %}